# Stage 1: Build the React Application
FROM node:20-alpine as build

WORKDIR /app

COPY netflex-onu-manager/package*.json ./
RUN npm install

COPY netflex-onu-manager/ .
RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

COPY nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
